[tool.poetry]
name = "stabs"
version = "0.1.0"
description = ""
authors = ["Iram Luis Morales Santos <iramluism@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
